## YAML Template.

development: &DEFAULT
  timeout: 30
  start_game_after: 10
  emulate_vm: true
  watch_folder: tmp/vmwatch

production:
  timeout: 300
  start_game_after: 120
  watch_folder: public/system/vmwatch
  client_tmp_folder: /home/scadmin/tmp
  server_host: 192.168.56.2
  silent: false
 
staging: 
  <<: *DEFAULT

test:
  <<: *DEFAULT
